# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

lista1 = ["1", "2", "3"]
lista2 = lista1 # Intentamos hacer una copia de la lista lista1
print(lista1, lista2)
del lista1[1] # Eliminamos el elemento ['2'] de la lista lista1 ...
print(lista1, lista2) # también ha desaparecido de la lista lista2