# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

compañeros=["Laura","Marta","Mateo","Juan","Vanesa","Simon","Domingo"]
print(compañeros[2:5]) # Se extrae una lista con los valores 2, 3 y 4
print(compañeros[4:5]) # Se extrae una lista con el valor 4
print(compañeros[4:4]) # Se extrae una lista vacía
print(compañeros[:4]) # Se extrae una lista hasta el valor 4 (no incluido)
print(compañeros[4:]) # Se extrae una lista desde el valor 4 (incluido)
print(compañeros[:]) # Se extrae una lista con todos los valores