# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

a = 198
b = a # Hacemos una copia del valor de a
print(a, b)
a = 25 # de manera que aunque cambiemos el valor de a ...
print(a, b) # conserva el valor anterior de a en caso de necesitarlo