# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

a = ("peru","europa","españa","peru","argentina","peru","italia")
print(a)
print("argentina" in a)
print(a.count("peru"))