# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

letras = ["A", "B", "C", "D", "E", "F", "G", "H"]
del letras[4] # Elimina la sublista ['E']
print(letras)
del letras[1:4] # Elimina la sublista ['B', 'C', 'D']
print(letras)
del (letras[0:10]) # Elimina completamente la lista
print(letras)