# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

personas = ("Ana", "brigida", "María", "Carina", "Ana", "Sofía", "brigida")

print(personas)                      # Muestra toda la tupla
print("Carina" in personas)          # ¿Está Carina en la tupla?
print(personas.count("Ana"))         # ¿Cuántas veces aparece Ana?
print(personas.index("brigida"))        # ¿En qué posición aparece la primera vez brigida?