# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

tup =(1,['a','e','i','o','u'],8.9,'buenos dias')
print(tup)