# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

paises = ("México", "Argentina", "Chile", "Perú", "México", "Colombia", "Chile")

print(paises)                    # Muestra toda la tupla
print("Peru" in paises)          # ¿Está Perú en la tupla?
print(paises.count("México"))    # ¿Cuántas veces aparece México?
print(paises.index("Chile"))     # ¿En qué posición aparece la primera vez Chile?