# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

letras = ["D", "E", "F"]
letras[3:3] = ["G", "H"] # Añade ["G", "H"] al final de la lista
print(letras)
letras[100:100] = ["I", "J"] # Añade ["I", "J"] al final de la lista
print(letras)
letras[-100:-50]=["A", "B", "C"] #Añade ["A", "B", "C"] al principio de la lista
print(letras)