# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

letras = ["A", "E", "I", "O", "U"]
letras[3:3] = ["AE", "AI"] # Añade ["AE", "AI"] al final de la lista
print(letras)
letras[100:100] = ["IO", "OU"] # Añade ["IO", "OU"] al final de la lista
print(letras)
letras[-100:-50]=["A", "B", "C"] #Añade ["A", "B", "C"] al principio de la lista
print(letras)