# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

a=(11,22,33,44)
print(a)
b=(66,"cetpro",88.25,"A",-23.2)
print(b)