# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

a=(1,2,3,4)
print(a)
b=(5,"cetpro",4.7,"A",-6.2)
print(b)