# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

letras = ["ANA", "BELEN", "CARLA", "DANIEL", "ESTEFANI", "FERNANDA", "GAEL"]
del letras[3] # Elimina la sublista ['DANIEL']
print(letras)
del letras[1:3] # Elimina la sublista ['BELEN', 'CARLA']
print(letras)
del (letras[0:9]) # Elimina completamente la lista
print(letras)