# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

dias=["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"]
print(dias[1:4]) # Se extrae una lista con los valores 1, 2 y 3
print(dias[4:5]) # Se extrae una lista con el valor 4
print(dias[4:4]) # Se extrae una lista vacía
print(dias[:4]) # Se extrae una lista hasta el valor 4 (no incluido)
print(dias[4:]) # Se extrae una lista desde el valor 4 (incluido)
print(dias[:]) # Se extrae una lista con todos los valores