# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

letras = ["A", "B", "C", "D", "E", "F", "G", "H"]
letras[3:4] = ["X"] #Se sustituye la sublista ['B','C','D'] por ['X']
print(letras)
letras[2:4]=["Y","Z"]#sustituye ['X','E','F'] por ['Y','Z']
print(letras)
letras[0:1] = ["Q"] # Se sustituye la sublista ['A'] por ['Q']
print(letras)
letras[2:2]=["U","V"]# Inserta la lista ['U','V'] en la posición 3
print(letras)
letras[0:3] = [] # Elimina la sublista ['Q','Y', 'Z']
print(letras)