# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUk4et8bO7IlFpwHeP2J9BxFSRSzmC5Q
"""

t = (1, "a", 3.14, True)
print(len(t))   # 4 elementos
texto = "Hola mundo"
print(len(texto))   # cuenta los caracteres (incluye espacio)
dicc = {"a": 1, "b": 2, "c": 3}
print(len(dicc))   # cuenta las llaves